version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
    volumes:
      - ./public:/app/public
    networks:
      envoymesh:
        aliases:
          - app
    expose:
      - "8081"
    ports:
      - "8081:5000"

networks:
  envoymesh:
    ipam:
      driver: default
      config:
      - subnet: 172.16.0.0/16
        gateway: 172.16.0.1