version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
    volumes:
      - ./public:/app/public
    expose:
      - ${PORT}
    ports:
      - ${PORT}:5000

networks:
  default:
    external:
      name: share_network